### ISSUE TITLE
导出无标签图片的.txt

### ISSUE THREAD

**Issue by FYM1209** [AlibabaResearch/efficientteacher#13]
无法导出无标签图片的.txt
![image](https://user-images.githubusercontent.com/93715148/222947945-1e0d106c-4aff-4b75-bb8d-91945b317c20.png)

**Comment by BowieHsu** [comment]
看起来像是那个目录下没有图片？可以ls检查一下吗？ @FYM1209

**Comment by FYM1209** [comment]
> 看起来像是那个目录下没有图片？可以ls检查一下吗？ @FYM1209

![image](https://user-images.githubusercontent.com/93715148/222949487-8fc7e783-7abc-414b-9872-8193909a0b21.png)
有的

**Comment by BowieHsu** [comment]
老师，试试把路径两边的尖括号去掉呢

**Comment by FYM1209** [comment]
> 老师，试试把路径两边的尖括号去掉呢

ok了

**Comment by FYM1209** [comment]
> 老师，试试把路径两边的尖括号去掉呢
Python==3.9还是3.8

**Comment by FYM1209** [comment]
![image](https://user-images.githubusercontent.com/93715148/222951688-10cf3bab-7de9-4bd7-8e49-dc226764bd8b.png)
版本按着文档要求的，但还是报这个错

**Comment by BowieHsu** [comment]
您好，我检查了一下scikit-learn的版本是这个，您看看您的运行环境是和这个对上的吗
![截屏2023-03-05 下午8 32 58](https://user-images.githubusercontent.com/4092342/222960696-8b5d584c-259d-4b24-bbc8-6bd83c3a128c.png)

**Comment by FYM1209** [comment]
> 您好，我检查了一下scikit-learn的版本是这个，您看看您的运行环境是和这个对上的吗 ![截屏2023-03-05 下午8 32 58](https://user-images.githubusercontent.com/4092342/222960696-8b5d584c-259d-4b24-bbc8-6bd83c3a128c.png)

这个问题已经解决了 但是在开始训练的时候，就直接结束了
![image](https://user-images.githubusercontent.com/93715148/223053256-94d22b35-dd21-40df-b030-1451b0c40c79.png)
是我的she'be设备不行么

**Comment by lonelyzyp** [comment]
> 看起来像是那个目录下没有图片？可以ls检查一下吗？ @FYM1209
    convert_yolov5_to_efficient( '/python_workspace/efficientteacher/weights/efficient-yolov5s.pt', '/python_workspace/efficientteacher/configs/ssod/custom/yolov5s_custom_ssod.yaml','/python_workspace/efficientteacher/weights/efficient-yolov5s.pt')
![image](https://user-images.githubusercontent.com/43600636/223760257-72c50dfd-16db-4683-beec-77a4257a3d9a.png)
你好，（Windows环境）请问在使用convert_pt_to_efficient.py把自己的pt导出为本项目可识别的pt文件时。出现了这种错误，如何解决呢

**Comment by BowieHsu** [comment]
@lonelyzyp 您好，像是路径填错了？ 需要把代码里的path填成您放权重的绝对路径。

**Comment by BowieHsu** [comment]
您好，需要用的yaml文件为sup文件夹哈，或者把您现在用的那个yaml文件里SSOD那一行以下的全注释掉应该就好了

**Comment by lonelyzyp** [comment]
> 您好，需要用的yaml文件为sup文件夹哈，或者把您现在用的那个yaml文件里SSOD那一行以下的全注释掉应该就好了
您好啊，在！我按照你说的使用sup文件夹，并且换成为5s的因子和，nc、names也修改。出现了以下问题，请问如何解决呢（双手合十）

Model summary: 268 layers, 7022326 parameters, 7022326 gradients

load weights from u-yolov5...
Traceback (most recent call last):
  File "G:/python_workspace/efficientteacher/scripts/mula_convertor/convert_pt_to_efficient.py", line 92, in <module>
    convert_yolov5_to_efficient( 'G:\python_workspace\efficientteacher\weights\yolov5s.pt', 'G:\python_workspace\efficientteacher\configs\sup\custom\yolov5s_custom.yaml','G:\python_workspace\efficientteacher\weights\efficient-yolov5s.pt')
  File "G:/python_workspace/efficientteacher/scripts/mula_convertor/convert_pt_to_efficient.py", line 44, in convert_yolov5_to_efficient
    model.load_state_dict(new_yolov5s_weight,strict=False)
  File "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\nn\modules\module.py", line 1407, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
	size mismatch for backbone.stage5_2.cv2.conv.weight: copying a param with shape torch.Size([512, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 512, 1, 1]).
	size mismatch for backbone.stage5_2.cv2.bn.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for backbone.stage5_2.cv2.bn.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for backbone.stage5_2.cv2.bn.running_mean: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for backbone.stage5_2.cv2.bn.running_var: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for backbone.sppf.cv2.conv.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([512, 1024, 1, 1]).
	size mismatch for backbone.sppf.cv2.bn.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for backbone.sppf.cv2.bn.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for backbone.sppf.cv2.bn.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for backbone.sppf.cv2.bn.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([512]).

Process finished with exit code 1

**Comment by BowieHsu** [comment]
您好，能检查一下您的原生YOLOv5版本吗，看起来像是结构和6.0的不一样

**Comment by lonelyzyp** [comment]
> 您好，能检查一下您的原生YOLOv5版本吗，看起来像是结构和6.0的不一样
好的，我重新开始检查，时间久了。再请问在power shell下使用时，出现这个问题。文件夹下存在图片
![image](https://user-images.githubusercontent.com/43600636/223772451-fcf356d6-ccbe-4f99-b7b5-7c5f7bdd4bb3.png)

**Comment by lonelyzyp** [comment]
> @lonelyzyp 您好，应该是使用Select-String 替换find命令，具体的使用方法您可以查查

好的，我尝试以下，特别感谢您的答疑，夜已深早点休息，期待和您之后的交流

**Comment by lonelyzyp** [comment]
@BowieHsu 您好！我换用YOLOV5s-6.0训练后权重，成功转换为本项目可识别模型。下面再训练用遇到两个问题，向您请教！
（1）当我使用自己备好的数据集时，使用（python train.py --cfg configs/ssod/custom/yolov5s_custom_ssod.yaml）
加载有标签数据时，不断出现OSError: [WinError 1455] 页面文件太小，无法完成操作；
 Error loading "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.；之后加载完成（Scanning 'data\ear3000_angel\train300labels' images and labels...300 found, 0 missing, 0 empty, 0 corrupted: 100%|）；最后报错BrokenPipeError: [Errno 32] Broken pipe，无法进行下一步
![image](https://user-images.githubusercontent.com/43600636/223972872-08075b6e-b923-4adc-b5c3-eb49cc95f89a.png)

**Comment by lonelyzyp** [comment]
> @BowieHsu 您好！我换用YOLOV5s-6.0训练后权重，成功转换为本项目可识别模型。下面再训练用遇到两个问题，向您请教！ （1）当我使用自己备好的数据集时，使用（python train.py --cfg configs/ssod/custom/yolov5s_custom_ssod.yaml） 加载有标签数据时，不断出现OSError: [WinError 1455] 页面文件太小，无法完成操作； Error loading "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.；之后加载完成（Scanning 'data\ear3000_angel\train300labels' images and labels...300 found, 0 missing, 0 empty, 0 corrupted: 100%|）；最后报错BrokenPipeError: [Errno 32] Broken pipe，无法进行下一步 ![image](https://user-images.githubusercontent.com/43600636/223972872-08075b6e-b923-4adc-b5c3-eb49cc95f89a.png)
仅改动yaml如下：改为5s的因子参数   nc:1     batch_size: 4(本地设定很小)，另外我没有找到num_workers控制线程，本地8核16线程CPU

**Comment by lonelyzyp** [comment]
@BowieHsu 当我使用（python val.py --cfg configs/sup/custom/yolov5s.yaml --weights weights/efficient-yolov5s.pt）进行val验证coco数据集，正常运行是否可以时。同样是“页面文件大小，无法完成操作”不停的跳动，最后完成了Val数据集5000张读取。然后就一直卡着不能正常进行了。
eg:
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies.
val: Scanning 'data\coco\val2017' images and labels...5000 found, 0 missing, 48 empty, 0 corrupted: 100%|██| 5000/5000 [01:06<00:00, 75.25it/s]

**Comment by Quintonkd** [comment]
win10 cuda11.7 i7-6700k rtx3080 python3.7 pytorch1.13存在同样的问题

**Comment by Quintonkd** [comment]
> @BowieHsu 当我使用（python val.py --cfg configs/sup/custom/yolov5s.yaml --weights weights/efficient-yolov5s.pt）进行val验证coco数据集，正常运行是否可以时。同样是“页面文件大小，无法完成操作”不停的跳动，最后完成了Val数据集5000张读取。然后就一直卡着不能正常进行了。 eg: OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies. val: Scanning 'data\coco\val2017' images and labels...5000 found, 0 missing, 48 empty, 0 corrupted: 100%|██| 5000/5000 [01:06<00:00, 75.25it/s]

win10 cuda11.7 i7-6700k rtx3080 python3.7 pytorch1.13存在同样的问题

**Comment by lonelyzyp** [comment]
> > @BowieHsu 当我使用（python val.py --cfg configs/sup/custom/yolov5s.yaml --weights weights/efficient-yolov5s.pt）进行val验证coco数据集，正常运行是否可以时。同样是“页面文件大小，无法完成操作”不停的跳动，最后完成了Val数据集5000张读取。然后就一直卡着不能正常进行了。 eg: OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "D:\Anaconda\envs\yolov5_ssda2\lib\site-packages\torch\lib\cudnn_cnn_infer64_8.dll" or one of its dependencies. val: Scanning 'data\coco\val2017' images and labels...5000 found, 0 missing, 48 empty, 0 corrupted: 100%|██| 5000/5000 [01:06<00:00, 75.25it/s]
> 
> win10 cuda11.7 i7-6700k rtx3080 python3.7 pytorch1.13存在同样的问题

您好，目前我的问题也是如此，在一台128GB RAM的服务器可以run，但还有其他问题正在处理，我通过问博主和查询，原因有1：机器RAM不足，比如我的24GB RAM  2：伪标签产生量比较多。您可以参考这https://github.com/AlibabaResearch/efficientteacher/issues/18#issuecomment-1463208347
希望对您有所帮助，
