### ISSUE TITLE
NameError: name 'ComputeFastXLoss' is not defined

### ISSUE THREAD

**Issue by yjcreation** [AlibabaResearch/efficientteacher#21]
![image](https://user-images.githubusercontent.com/22938656/224310383-a774d6c1-d5e5-4135-a046-d591baf3b781.png)
您好！拉取最新的代码后，依然遇到该问题，请问一下该问题如何解决？我在配置文件中加载了`efficient-yolov7s-simota.pt`权重
@BowieHsu

**Comment by BowieHsu** [comment]
不要慌，我查一下，问题不大

**Comment by yjcreation** [comment]
> 不要慌，我查一下，问题不大

好的，非常感谢！请问检查完了吗？ @BowieHsu

**Comment by yjcreation** [comment]
您好，训练之后遇到如下问题：
![image](https://user-images.githubusercontent.com/22938656/224457376-544bbc7b-2c37-4775-aa92-6c04e172aed6.png)
 @BowieHsu

**Comment by BowieHsu** [comment]
好的，我复现一下

**Comment by yjcreation** [comment]
> 好的，我复现一下

您好，请问解决了吗

**Comment by BowieHsu** [comment]
![截屏2023-03-12 下午3 01 53](https://user-images.githubusercontent.com/4092342/224529578-0d0811f2-6035-4dc7-9a45-d590b9217706.png)
@yjcreation 您好，我这边测了几次都是能成功运行的，还有更多的信息能提供吗

**Comment by yjcreation** [comment]
> ![截屏2023-03-12 下午3 01 53](https://user-images.githubusercontent.com/4092342/224529578-0d0811f2-6035-4dc7-9a45-d590b9217706.png) @yjcreation 您好，我这边测了几次都是能成功运行的，还有更多的信息能提供吗

问题不在这里。一共300轮，在最后一轮结束的时候，在验证时出现该问题。我之前同时跑了两种不同的数据比例，都出现同样的错误。
```
alidating runs/yolov7/simota/5_percent/exp/weights/best.pt...
Fusing layers... 
Model summary: 349 layers, 9441572 parameters, 1549184 gradients
                 all        600       3238       0.87      0.844      0.885      0.784
Optimizer stripped from runs/yolov7/simota/5_percent/exp/weights/last.pt, 19.6MB
Optimizer stripped from runs/yolov7/simota/5_percent/exp/weights/best.pt, 19.6MB
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block
RepConv.fuse_repvgg_block

               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/19 [00:00<?, ?it/s]
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95:   0%|          | 0/19 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train5.py", line 84, in <module>
    main(opt)
  File "train5.py", line 76, in main
    trainer.train(callbacks, val)
  File "/home/xxx/efficientteacher/trainer/trainer.py", line 539, in train
    results = self.after_train(callbacks, val)
  File "/home/xxx/efficientteacher/trainer/trainer.py", line 502, in after_train
    results, _, _ = val.run(self.data_dict,
  File "/home/xxx/miniconda3/envs/general/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/efficientteacher/val.py", line 297, in run
    outputs = model(img, augment=augment)  # inference and training outputs
  File "/home/xxx/miniconda3/envs/general/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/efficientteacher/models/detector/yolo.py", line 88, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "/home/xxx/log/4.semi-supervised/2023-3-10/efficientteacher/models/detector/yolo.py", line 93, in _forward_once
    x = self.head(x)
  File "/home/xxx/miniconda3/envs/general/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/efficientteacher/models/head/yolox_head.py", line 351, in forward
    y[..., 0:2] = (y[..., 0:2] + self.grid[i]) * self.stride[i]  # xy
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

```
@BowieHsu

**Comment by BowieHsu** [comment]
哦哦 了解，那应该不影响训练，我再查一下，目前这个loss试下来有帮助吗

**Comment by yjcreation** [comment]
> 



> 共300轮，在最后一轮结束的时候，在验证时出现该问题。我之前同时跑了两种不同的数据比例，都出现同样的错误。是不是尝试直接将300设为很小的轮数，看训练结束之后是否出现如下问题
> 
> ```
> alidating runs/yolov7/simota/5_percent/exp/weights/best.pt...
> ```

之前在v5上面，先在有标签的数据（大约4000多张出头）上预训练好一个权重，测试得到结果1；然后在大约1000张无标注的图片上进行半监督的训练，20轮，测试得到结果2，发现和1的结果几乎一模一样。有的结果还没整理好，等我多测试几组，反应一下结果

**Comment by yjcreation** [comment]
您好，请问解决了吗 @BowieHsu

**Comment by xiaowu77** [comment]
> 您好，训练之后遇到如下问题： ![image](https://user-images.githubusercontent.com/22938656/224457376-544bbc7b-2c37-4775-aa92-6c04e172aed6.png) @BowieHsu

我在训练yolox 的时候也遇到了这个问题，我修改了一下 yolox_head.py 中351行的代码 
y[..., 0:2] = (y[..., 0:2] + self.grid[i]) * self.stride[i] 
修改如下：
y[..., 0:2] = (y[..., 0:2] + self.grid[i].to(x[i].device)) * self.stride[i]
就能正常跑通了
