### ISSUE TITLE
请问有人在efficientteacher上使用yolov7进行半监督训练吗

### ISSUE THREAD

**Issue by liuxuet** [AlibabaResearch/efficientteacher#24]

**Comment by yjcreation** [comment]
> _No description provided._

有，目前正在进行中，遇到点问题

**Comment by liuxuet** [comment]
> 

是要对IDetect进行修改吗，且需要在yolo_ssod.py的中check_head方法中添加IDetect吗，我目前感觉是这样的，请问你是怎么改的呢？

**Comment by liuxuet** [comment]
> > _No description provided._
> 
> 有，目前正在进行中，遇到点问题

是要对IDetect进行修改吗，且需要在yolo_ssod.py的中check_head方法中添加IDetect吗，我目前感觉是这样的，请问你是怎么改的呢？

**Comment by liuxuet** [comment]
> > _No description provided._
> 
> 有，目前正在进行中，遇到点问题

你好，我将yolov7的head改为yolov5的head之后可以跑起来

**Comment by yjcreation** [comment]
> > > _No description provided._
> > 
> > 
> > 有，目前正在进行中，遇到点问题
> 
> 你好，我将yolov7的head改为yolov5的head之后可以跑起来
我参考的是yolov7s_coco_simota.yaml配置文件，目前正在修改

**Comment by liuxuet** [comment]
> @yjcreation @liuxuet 不好意思，那块写残了，我添加一下对Idetect的支持

好的，谢谢

**Comment by kikucxj** [comment]
> > @yjcreation @liuxuet 不好意思，那块写残了，我添加一下对Idetect的支持
> 
> 好的，谢谢

请问试过更新后的版本吗，效果和之前比怎么样呀

**Comment by BowieHsu** [comment]
@kikucxj 我们更新了对Idetect的支持，原来是默认调用YOLOv5的detect，现在正在测试

**Comment by colorfulandcjy0806** [comment]
> @kikucxj 我们更新了对Idetect的支持，原来是默认调用YOLOv5的detect，现在正在测试

您好，请问一下，当我在进行YOLOv7的半监督训练的时候，发生了AttributeError: 'Model' object has no attribute 'stride'的错误，但是当我将yaml里面的train_domain: True注释掉后，就可以正常运行了，您可以告诉我原因吗？

**Comment by BowieHsu** [comment]
@colorfulandcjy0806 您好，有更详细的报错信息可以贴一下吗

**Comment by colorfulandcjy0806** [comment]
> @colorfulandcjy0806 您好，有更详细的报错信息可以贴一下吗
错误信息是这样的：
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(opt)
  File "train.py", line 72, in main
    trainer = SSODTrainer(cfg, device, callbacks, LOCAL_RANK, RANK, WORLD_SIZE)
  File "/root/autodl-tmp/et/trainer/ssod_trainer.py", line 60, in __init__
    self.build_dataloader(cfg, callbacks)
  File "/root/autodl-tmp/et/trainer/ssod_trainer.py", line 207, in build_dataloader
    gs = max(int(self.model.stride.max()), 32)  # grid size (max stride)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Model' object has no attribute 'stride'

**Comment by BowieHsu** [comment]
@colorfulandcjy0806 您能git pull拉取一下最新代码吗，这个问题应该已经解掉了，我们测试了IDetect是能够跑半监督的

**Comment by colorfulandcjy0806** [comment]
@BowieHsu 太感谢了，当我重新拉取代码后，问题解决了，谢谢您！

**Comment by xiaohui0225** [comment]
> @BowieHsu 太感谢了，当我重新拉取代码后，问题解决了，谢谢您！

请问，您在使用yolov7进行半监督时，是如何将标准的yolov7.pt转成efficient_yolov7.pt的？除此之外，还有哪里需要修改来适配yolov7？

**Comment by greedy-hat** [comment]
请问一下，yolov7的网络结构被魔改之后，还能用efficient teacher来进行半监督训练

**Comment by jaideep11061982** [comment]
@BowieHsu @greedy-hat 
if i understand the latest version Idetect should be working fine for YOlov7 . But how to get map.txt for converting to efficient yolov7 ?
Thanks in advance

**Comment by delicate00** [comment]
> @yjcreation @liuxuet 不好意思，那块写残了，我添加一下对Idetect的支持

作者您好，yolov7添加IDetect以后跑确实是可以跑起来，但是前50代左右数值全为0，哪怕是加了预训练权重也是如此。但是将使用'YOLOv5'用作head就没有问题，训练出来的数值提升明显，请问是因为v7 head这块需要再完善一下吗

**Comment by TahereSaidi** [comment]
@xiaohui0225 Hi. Were you able to solve the problem?
I also don't know how to convert YOLO V8 to efficient_yolov8.pt. If you know what to do for Yolo V7, can you guide me?

**Comment by hecheng000** [comment]
> I also don't know how to convert YOLO V8 to efficient_yolov8.pt. If you know what to do for Yolo V7, can 

> > @yjcreation @liuxuet 不好意思，那块写残了，我添加一下对Idetect的支持
> 
> 作者您好，yolov7添加IDetect以后跑确实是可以跑起来，但是前50代左右数值全为0，哪怕是加了预训练权重也是如此。但是将使用'YOLOv5'用作head就没有问题，训练出来的数值提升明显，请问是因为v7 head这块需要再完善一下吗

你好 可以分享下跑通的v7版本吗 可有偿

**Comment by yushuz** [comment]
转成efficient-yolov7.pt之后，在自己的测试集上测出来指标跟原来的相比，差异在多少以内算正常呀？大家转完之后会掉点吗？
