### ISSUE TITLE
pt文件转换问题

### ISSUE THREAD

**Issue by xiaohui0225** [AlibabaResearch/efficientteacher#43]
我在训练好efficient_yolol.pt之后，使用convert_efficient_to_yolov5转换成标准的yolov5l.pt，但在使用yolov5官方的detect.py时，出现了以下bug：
Traceback (most recent call last):
  File "/home/***/Desktop/workspace/yolov5/detect.py", line 307, in <module>
    main(opt)
  File "/home/***/Desktop/workspace/yolov5/detect.py", line 302, in main
    run(**vars(opt))
  File "/usr/local/anaconda3/envs/***/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/***/Desktop/workspace/yolov5/detect.py", line 82, in run
    model = torch.jit.load(w) if 'torchscript' in w else attempt_load(weights, map_location=device)
  File "/home/***/Desktop/workspace/yolov5/models/experimental.py", line 94, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/***/Desktop/workspace/yolov5/models/yolo.py'>

**Comment by Dong-tranction** [comment]
您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的
<img width="561" alt="屏幕截图 2023-03-22 170831" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">

**Comment by Dong-tranction** [comment]
> 我在训练好efficient_yolol.pt之后，使用convert_efficient_to_yolov5转换成标准的yolov5l.pt，但在使用yolov5官方的detect.py时，出现了以下bug： Traceback (most recent call last): File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 307, in main(opt) File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 302, in main run(* * vars(opt)) File "/usr/local/anaconda3/envs/***/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, * * kwargs) File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 82, in run model = torch.jit.load(w) if 'torchscript' in w else attempt_load(weights, map_location=device) File "/home/zzz/Desktop/workspace/yolov5/models/experimental.py", line 94, in attempt_load ckpt = torch.load(attempt_download(w), map_location=map_location) # load File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 607, in load return _load(opened_zipfile, map_location, pickle_module, * * pickle_load_args) File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load result = unpickler.load() File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class return super().find_class(mod_name, name) **AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/zzz/Desktop/workspace/yolov5/models/yolo.py'>**

您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的

**Comment by xiaohui0225** [comment]
> 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">

把您的配置数据的yaml发我看一下。

**Comment by Dong-tranction** [comment]
> > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> 
> 把您的配置数据的yaml发我看一下。

<img width="587" alt="屏幕截图 2023-03-23 105140" src="https://user-images.githubusercontent.com/71391484/227088351-daa2e80b-c618-458e-9875-e15eebac4e61.png">
<img width="831" alt="屏幕截图 2023-03-23 105156" src="https://user-images.githubusercontent.com/71391484/227088357-670a94ce-d6ec-4cd1-a496-0c1d4d57d1dd.png">
<img width="318" alt="屏幕截图 2023-03-23 105212" src="https://user-images.githubusercontent.com/71391484/227088360-1f78cf50-0306-43a1-8017-ac1a6b2c8663.png">

**Comment by xiaohui0225** [comment]
你把burn_epochs设置成0试试。

**Comment by xiaohui0225** [comment]
> > > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> > 
> > 
> > 把您的配置数据的yaml发我看一下。
> 
> <img alt="屏幕截图 2023-03-23 105140" width="587" src="https://user-images.githubusercontent.com/71391484/227088351-daa2e80b-c618-458e-9875-e15eebac4e61.png">
> 
> <img alt="屏幕截图 2023-03-23 105156" width="831" src="https://user-images.githubusercontent.com/71391484/227088357-670a94ce-d6ec-4cd1-a496-0c1d4d57d1dd.png">
> 
> <img alt="屏幕截图 2023-03-23 105212" width="318" src="https://user-images.githubusercontent.com/71391484/227088360-1f78cf50-0306-43a1-8017-ac1a6b2c8663.png">

你把burn_epochs设置成0试试

**Comment by xiaohui0225** [comment]
你的训练指令是什么？

**Comment by xiaohui0225** [comment]
> > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> 
> 把您的配置数据的yaml发我看一下。

你的训练指令是什么？

**Comment by xiaohui0225** [comment]
> 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">

你的训练指令是什么？

**Comment by Dong-tranction** [comment]
> > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> 
> 你的训练指令是什么？

<img width="960" alt="屏幕截图 2023-03-23 130848" src="https://user-images.githubusercontent.com/71391484/227109070-57b3e60a-c653-4ee1-9056-1fa2310bc277.png">
burn_epochs设置0也没有作用

**Comment by xiaohui0225** [comment]
> > > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> > 
> > 
> > 你的训练指令是什么？
> 
> <img alt="屏幕截图 2023-03-23 130848" width="960" src="https://user-images.githubusercontent.com/71391484/227109070-57b3e60a-c653-4ee1-9056-1fa2310bc277.png">
> 
> burn_epochs设置0也没有作用

ssdo_hyp的with_gt应该设置成False，你设置成了True，应该是默认你的unlabel数据也是有gt的。
顺便问一句，阿里只给了yolov5l的custom.yaml，你是仿照哪个文件写的yolov5s.yaml的？

**Comment by xiaohui0225** [comment]
> > > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> > 
> > 
> > 你的训练指令是什么？
> 
> <img alt="屏幕截图 2023-03-23 130848" width="960" src="https://user-images.githubusercontent.com/71391484/227109070-57b3e60a-c653-4ee1-9056-1fa2310bc277.png">
> 
> burn_epochs设置0也没有作用

ssod_hyp的with_gt应该设置成False，你设置成了True，应该是默认你的unlabel数据也是有gt的。
顺便问一句，阿里只给了yolov5l的custom.yaml，你是仿照哪个文件写的yolov5s.yaml的

**Comment by Dong-tranction** [comment]
> > > > 您好，请问您开始训练的时候不会报找不到target里的图片标签的错误吗？请问您的数据集格式是什么样子的 <img alt="屏幕截图 2023-03-22 170831" width="561" src="https://user-images.githubusercontent.com/71391484/227086749-46e32dce-76ec-4b39-ae3d-98dd7466f328.png">
> > > 
> > > 
> > > 你的训练指令是什么？
> > 
> > 
> > <img alt="屏幕截图 2023-03-23 130848" width="960" src="https://user-images.githubusercontent.com/71391484/227109070-57b3e60a-c653-4ee1-9056-1fa2310bc277.png">
> > burn_epochs设置0也没有作用
> 
> ssod_hyp的with_gt应该设置成False，你设置成了True，应该是默认你的unlabel数据也是有gt的。 顺便问一句，阿里只给了yolov5l的custom.yaml，你是仿照哪个文件写的yolov5s.yaml的

作者工程代码里面的yaml文件很多，按照readme上面的指示我并没有找到对应目录下的yaml文件，不知道是不是作者忘记更新readme了，我是参考这个目录下的yaml写的configs/ssod/custom/yolov5l_custom_ssod.yaml
顺便问一下，你找到了作者readme里面说明的那个yaml文件了吗？

**Comment by Jayus-su** [comment]
> 我在训练好efficient_yolol.pt之后，使用convert_efficient_to_yolov5转换成标准的yolov5l.pt，但在使用yolov5官方的detect.py时，出现了以下bug： Traceback (most recent call last): File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 307, in main(opt) File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 302, in main run(* * vars(opt)) File "/usr/local/anaconda3/envs/***/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, * * kwargs) File "/home/zzz/Desktop/workspace/yolov5/detect.py", line 82, in run model = torch.jit.load(w) if 'torchscript' in w else attempt_load(weights, map_location=device) File "/home/zzz/Desktop/workspace/yolov5/models/experimental.py", line 94, in attempt_load ckpt = torch.load(attempt_download(w), map_location=map_location) # load File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 607, in load return _load(opened_zipfile, map_location, pickle_module, * * pickle_load_args) File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 882, in _load result = unpickler.load() File "/usr/local/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/serialization.py", line 875, in find_class return super().find_class(mod_name, name) **AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from '/home/zzz/Desktop/workspace/yolov5/models/yolo.py'>**

您好，碰到了同样的问题，请问现在解决了吗
