### ISSUE TITLE
读取unlabel数据时出现OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\useful-tool\Anaconda\envs\cnm\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by perllK** [AlibabaResearch/efficientteacher#83]
您好！ 
        感谢您的分享！有如下问题，烦请空闲时解答！万分感谢
        我将number = 0 batchsize = 2，但是在跑代码时依然出现如下错误：
target: Scanning 'data\custom_unlabeled' images and labels...:   0%|          | 0/525 [00:00<?, ?it/s]Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\useful-tool\Anaconda\envs\cnm\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\useful-tool\Anaconda\envs\cnm\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\useful-tool\Anaconda\envs\cnm\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\useful-tool\Anaconda\envs\cnm\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\useful-tool\Anaconda\envs\cnm\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\useful-tool\Anaconda\envs\cnm\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\useful-tool\Anaconda\envs\cnm\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\v7-semi\efficientteacher-main\efficientteacher-main\train.py", line 2, in <module>
    import torch
  File "E:\useful-tool\Anaconda\envs\cnm\lib\site-packages\torch\__init__.py", line 123, in <module>
    raise err
OSError: [WinError 1455] 页面文件太小，无法完成操作。 Error loading "E:\useful-tool\Anaconda\envs\cnm\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

**Comment by perllK** [comment]
补充：随后我又测试了几次，发现出现这种情况则不会生成cache文件。

**Comment by KUN-1125** [comment]
我在自己笔记本上调试的时候也是这样，猜测可能是内存不够，上服务器跑就没问题了。

**Comment by kv1830** [comment]
可以看看这个：
https://blog.csdn.net/ogebgvictor/article/details/130468704
