### ISSUE TITLE
请问ssod设置为debug=True后还需要修改哪些才能成功保存？

### ISSUE THREAD

**Issue by KUN-1125** [AlibabaResearch/efficientteacher#96]
设置为debug=True后报错：
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(opt)
  File "train.py", line 76, in main
    trainer.train(callbacks, val)
  File "/home/kun_465h/jupyterlab/efficientteacher/trainer/trainer.py", line 535, in train
    self.train_in_epoch(callbacks)
  File "/home/kun_465h/jupyterlab/efficientteacher/trainer/ssod_trainer.py", line 317, in train_in_epoch
    self.train_with_unlabeled(callbacks)
  File "/home/kun_465h/jupyterlab/efficientteacher/trainer/ssod_trainer.py", line 697, in train_with_unlabeled
    self.train_instance(imgs, targets, paths, target_imgs, target_imgs_ori, target_gt, target_M, ni, pbar, callbacks)
  File "/home/kun_465h/jupyterlab/efficientteacher/trainer/ssod_trainer.py", line 618, in train_instance
    unlabeled_targets, invalid_target_shape = self.pseudo_label_creator.create_pseudo_label_online_with_gt(teacher_pred, copy.deepcopy(unlabeled_imgs), unlabeled_M, copy.deepcopy(unlabeled_imgs_ori), unlabeled_gt, self.RANK)
  File "/home/kun_465h/jupyterlab/efficientteacher/utils/self_supervised_utils.py", line 241, in create_pseudo_label_online_with_gt
    draw_image = plot_images_ssod(copy.deepcopy(target_imgs), target_out_targets_perspective, fname='/mnt/bowen/EfficientTeacher/effcient_teacher_pseudo_label.jpg', names=self.names)            
  File "/home/kun_465h/jupyterlab/efficientteacher/utils/plots.py", line 697, in plot_images_ssod
    annotator.im.save(fname)  # save
  File "/home/kun_465h/.local/lib/python3.7/site-packages/PIL/Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/bowen/EfficientTeacher/effcient_teacher_pseudo_label.jpg'

**Comment by guixuef** [comment]
项目里搜 ：mnt/bowen/EfficientTeacher/effcient_teacher_pseudo_label.jpg 改成你电脑的路径就行了。

**Comment by KUN-1125** [comment]
感谢回答！

**Comment by wangsun1996** [comment]
请问训练过程中debug中保存下来的真实标签和生成伪标签的图片，里面有一些彩色的实心框，这个代表什么意思？在代码里没找到是在哪里叠加上去的
